name: Push Check

on:
  push:
    branches:
      - chaeseungyun
      - chohc51
      - dradnats1012
      - jeonghoon
      - leet3JH
      - mingu830
      - pocket
      - seunghui
      - sungwoo

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Get current date
      run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Backup existing README content
      run: cat README.md > README_backup.md

    - name: Update README
      run: |
        BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
        DATE=$DATE

        if ! grep -q "| Date       | chaeseungyun | chohc51 | dradnats1012 | jeonghoon | leet3JH | mingu830 | pocket | seunghui | sungwoo |" README.md; then
          echo -e "\n| Date       | chaeseungyun | chohc51 | dradnats1012 | jeonghoon | leet3JH | mingu830 | pocket | seunghui | sungwoo |\n|------------|--------------|--------|--------------|----------|--------|---------|--------|---------|--------|" > README_matrix.md
        else
          head -n 2 README.md > README_matrix.md
        fi

        if ! grep -q "$DATE" README.md; then
          echo -e "| $DATE |              |        |              |          |        |         |        |         |        |" | cat - README.md > temp && mv temp README.md
        fi

        sed -i "/| $DATE |/s/| $BRANCH_NAME |/| O |/g" README.md
        
        cat README_matrix.md README.md > README_combined.md
        mv README_combined.md README.md

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update README with latest push data"
        git pull origin main --strategy-option=theirs
        git push origin HEAD:main
      if: success()
